### ISSUE TITLE
不能上传

### ISSUE THREAD

**Issue by chenruifu** [yscoder/vscode-qiniu-upload-image#11]
从vscode安装，跟下载vsix安装  都不行
![image](https://user-images.githubusercontent.com/19771516/32089999-b3a0d1ca-bb1f-11e7-8535-a1584e52bbf6.png)

**Comment by yscoder** [comment]
检查你的配置：

```js
"qiniu.enable": true,  // 默认为 false
```

改变设置后重启 vscode
