### ISSUE TITLE
os x下无法监听到快捷键

### ISSUE THREAD

**Issue by moonou** [yscoder/vscode-qiniu-upload-image#2]
os x下`Ctrl+Shift+Q`无法唤醒插件，而是启用关机，当前打开的是`*.md`结尾的文件
![image](https://cloud.githubusercontent.com/assets/6938877/19843868/61dacc5e-9f61-11e6-9a60-b666dc029009.png)

**Comment by yscoder** [comment]
我没用过OSX，你有没有什么推荐的、安全的键位设置？

**Comment by moonou** [comment]
试了一下，在mac下换成ctrl+q也是没问题的
![image](https://cloud.githubusercontent.com/assets/6938877/19844047/6c3405e2-9f63-11e6-90ed-6c37d8a3cc67.png)
可以正常使用

**Comment by yscoder** [comment]
vs上更新了
