### ISSUE TITLE
command 'extension.qiniu.upload' not found

### ISSUE THREAD

**Issue by huichi2028** [yscoder/vscode-qiniu-upload-image#3]
这个插件不支持mac吗？
mac使用会报错
command 'extension.qiniu.upload' not found

**Comment by yscoder** [comment]
可以的啊。你是从vscode安装的还是用 `.vsix` 文件安装的？

**Comment by zhishuixx** [comment]
@yscoder  我的mac版也有这个提示.  我是直接在vscode安装的。

**Comment by edisonleolhl** [comment]
@favers @zhishuixx 
我的笔记本是 win 7 的，从 vscode 直接安装后，ctrl+p 也会出现"command 'extension.qiniu.upload' not found"
解决办法：在作者的项目中有 vsix 文件，在 vscode 扩展中心选择“从 VSIX 安装...”即可
 @yscoder 感谢作者

**Comment by fighting41love** [comment]
Same error. 在商店安装和.vsix安装同样报错。
Mac OS Majave
vscode 1.31.1
