### ISSUE TITLE
返回的没有域名 只有文件名

### ISSUE THREAD

**Issue by GuojieLin** [yscoder/vscode-qiniu-upload-image#4]
正确设置后返回了如：![图片名](图片名)，而不是![图片名](域名/图片名)，每次都要手动把域名加上。

**Comment by GuojieLin** [comment]
正确设置后返回了如：`![图片名](图片名.jpg)`，而不是`![图片名](域名/图片名.jpg)`，每次都要手动把域名加上。

**Comment by yscoder** [comment]
`qiniu.domain` 设置为你的七牛域名，`qiniu.bucket` 设置为你的图床空间名。

**Comment by GuojieLin** [comment]
您好:
    已经设置了
```
    "qiniu.bucket": "markdownimages",
    "qiniu.remotePath": "${dateTime}-${fileName}",
    "qiniu.domain": "7xl0cr.com1.z0.glb.clouddn.com"
```
域名是要加`http：//`吗？

**Comment by yscoder** [comment]
是的

**Comment by GuojieLin** [comment]
非常感谢,成功了。如果能支持截图直接上传就更棒了。现在每次都要把截图往qq输入框黏贴一下再复制到本地文件夹保存才可以。👍

**Comment by yscoder** [comment]
最初就是想通过 `复制图片 -> 粘贴到编辑器 ` 实现的，但是 vscode 没有提供对应操作的 API，只能妥协这样了。
如果之后有了相关 API 提供，我会第一时间更新的。
