### ISSUE TITLE
升级后不能使用了

### ISSUE THREAD

**Issue by yoyofx** [yscoder/vscode-qiniu-upload-image#8]
vs code 版本 1.11.2

**Comment by yscoder** [comment]
上次更新主要是用 ES6 重写了代码，不知道是不是跟 Node 版本有关。你的 Node 版本如果是 v6 以下的话，升级到最新版试试。

**Comment by yoyofx** [comment]
我得版本是6.9.5应该不是node版本的问题



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
由： Yusen <notifications@github.com>
日期: 2017/4/17 18:50 (GMT+08:00)
收件人： yscoder/vscode-qiniu-upload-image <vscode-qiniu-upload-image@noreply.github.com>
抄送： max zhang <zl.hxd@hotmail.com>, Author <author@noreply.github.com>
主题： Re: [yscoder/vscode-qiniu-upload-image] 升级后不能使用了 (#8)


上次更新主要是用 ES6 重写了代码，不知道是不是跟 Node 版本有关。你的 Node 版本如果是 v6 以下的话，升级到最新版试试。

―

**Comment by yoyofx** [comment]
你那边插件是可用的吗，我还是不能用，很多人都反应这问题，node 版本 6.9.5。

**Comment by yscoder** [comment]
我可以用

**Comment by yscoder** [comment]
@maxzhang1985 你用 `.vsix` 包安装试试能不能用
