### ISSUE TITLE
无法上传

### ISSUE THREAD

**Issue by guoxiangwen** [yscoder/vscode-qiniu-upload-image#9]
把你的代码放在 插件中跑了一下。

发现根本没传到七牛上去，config配置了 七牛信息了的

**Comment by yscoder** [comment]
你用 .vsix 包安装试试能不能用

**Comment by guoxiangwen** [comment]
你好，再问个问题，用的时候你的那些七牛的ac,ac,bucket是配置在哪里的？ 在开发插件过程中又是配置在哪里的？

**Comment by yscoder** [comment]
用户设置中

**Comment by guoxiangwen** [comment]
.vscode/settings.json中吗？

**Comment by yscoder** [comment]
`ctrl+,`

**Comment by guoxiangwen** [comment]
没有任何反应啊

**Comment by yscoder** [comment]
配置后重启下，另外是不显示输入框还是确认后不能生成链接？

**Comment by guoxiangwen** [comment]
不是，我是说 `ctrl+,`没有反应,开发的时候 只有在package.json中的configuration中配置才可以读取七牛信息么？

**Comment by yscoder** [comment]
`文件 -> 首选项 -> 设置`，我这里 `ctrl+,` 是打开设置的快捷键。
